[functions]
  directory = "functions"

[build]
  base = "./"
  command = "npm run build"
  publish = "dist"
  functions = "functions"
[dev]
  base = "./"
  command = "npm run dev"
  publish = "dist"
[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    include = ["CONTEXT"]
[build.environment]
  # Use a local non-Git-tracked .env file to set this to "development"; 
  # "netlify dev" picks up ".env" and "netlify build" does not.
  NODE_ENV = "production"