[build]
  base = "./"
  command = "pnpm run build"
  publish = "dist"
[dev]
  base = "./"
  command = "pnpm run dev"
  publish = "dist"
[build.environment]
  # Use a local non-Git-tracked .env file to set this to "development"; 
  # "netlify dev" picks up ".env" and "netlify build" does not.
  NODE_ENV = "production"