[functions]
  directory = "functions"

[functions."submission-created"]
  included_files = ["certs/bigbadcon-com-chain.pem"]

[build]
  base = "./"
  command = "npm run build"
  publish = "dist"
  functions = "functions"
[dev]
  base = "./"
  command = "npm run dev"
  publish = "dist"
[build.environment]
  # Use a local non-Git-tracked .env file to set this to "development"; 
  # "netlify dev" picks up ".env" and "netlify build" does not.
  NODE_ENV = "production"